### PR TITLE
ldap2s3 deprecated in favor of ldap_to_cis [IAM-858]

### PR DESCRIPTION
**Pull request by floatingatoll**

### CODE REVIEW

**Review by gcoxmoz — COMMENTED** [review]
I can't approve this because `ldap_to_cis` doesn't know about any dev environment.  If it ever did, it was likely in manual one-off tests that never got puppeted.  So `config.dev.yml` changes are unknowable/unverifiable to me.

Setting that aside, the names of file and prod bucket are right for prod, so that looks good.

**Comment by floatingatoll** [comment]
> I can't approve this because `ldap_to_cis` doesn't know about any dev environment. If it ever did, it was likely in manual one-off tests that never got puppeted. So `config.dev.yml` changes are unknowable/unverifiable to me.

Yep, that dev bucket doesn't exist, but at least now it'll produce a sensible 404 error that can be triaged without 'ldap2s3' getting in the mix.

**Comment by gcoxmoz** [comment]
My thought would then be a comment ala "we know this doesn't exist" or rename the bucket to "dev-cache.we.test.in.production."  But overall, if dev's known-hacky then this seems sane to land.

**Review by gcoxmoz — APPROVED** [review]
Approving because prod is sane and dev's deficiencies are considered (if not doc'ed).

**Pull request closed without merging**
